#:kivy 2.1.0
#:import Factory kivy.factory.Factory


<MainScreen>
    BoxLayout:
        orientation: "vertical"
        anchor_x:'right'
        anchor_y:'top'
        padding: dp(0), dp(0), dp(0), dp(5)
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)

            Rectangle:
                size: self.size
                pos: self.pos

        MDTopAppBar:
            orientation: "horizontal"
            title: root.AppName
            font_size: app.font_size
            specific_text_color:  get_color_from_hex(app.TC)
            anchor_title: "left"
            md_bg_color: get_color_from_hex(app.AC)
            elevation: 2

            MDIconButton:
                icon: "account-circle"
                theme_text_color: "Custom"
                text_color: get_color_from_hex(app.TC)
                size_hint_x: .2
                pos_hint: {'center_y': .5}
                on_release:
                    root.profile_btn_touch_up()

        BoxLayout:
            padding: dp(0), dp(10)
            spacing: dp(5)
            anchor_y:'top'
            orientation: "vertical"
            height: root.height

            DayButton:
                id: day0
                on_release:
                    root.day_btn_touch_up("day0")

            DayButton:
                text: "Button2"
                id: day1
                on_release:
                    root.day_btn_touch_up("day1")

            DayButton:
                text: "Button3"
                id: day2
                on_release:
                    root.day_btn_touch_up("day2")

            DayButton:
                text: "Button4"
                id: day3
                md_bg_color: get_color_from_hex(app.PBC)
                on_release:
                    root.day_btn_touch_up("day3")

            DayButton:
                    text: "Button5"
                id: day4
                on_release:
                    root.day_btn_touch_up("day4")

            DayButton:
                text: "Button6"
                id: day5
                on_release:
                    root.day_btn_touch_up("day5")

            DayButton:
                text: "Button7"
                id: day6
                on_release:
                    root.day_btn_touch_up("day6")


        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.1
            padding: dp(5)
            spacing: dp(10)

            MDFloatingActionButton:
                size_hint_x: .20
                icon: "check-decagram"
                md_bg_color: get_color_from_hex(app.PBC)
                icon_color: get_color_from_hex(app.TC)
                pos_hint: {"center_x": .9, "center_y": .5}
                on_release:
                    root.Task_btn_toch_up()

            MDFloatingActionButton:
                size_hint_x: .20
                icon: "calendar"
                md_bg_color: get_color_from_hex(app.PBC)
                icon_color: get_color_from_hex(app.TC)
                pos_hint: {"center_x": .9, "center_y": .5}
                on_release:
                    root.calendare_btn_toch_up()

            MDFloatingActionButton:
                size_hint_x: .20
                icon: "thumb-up"
                md_bg_color: get_color_from_hex(app.PBC)
                icon_color: get_color_from_hex(app.TC)
                pos_hint: {"center_x": .9, "center_y": .5}
                on_release:
                    root.rate_btn_touch_up()

            MDFloatingActionButton:
                size_hint_x: .20
                icon: "plus"
                md_bg_color: get_color_from_hex(app.PBC)
                icon_color: get_color_from_hex(app.TC)
                pos_hint: {"center_x": .9, "center_y": .5}
                on_release:
                    root.add_btn_touch_up()


<DayButton>
	text_color: get_color_from_hex(app.TC)
    font_size: app.font_size
    halign: 'left'
    valign: 'center'
    md_bg_color: get_color_from_hex(app.SBC)

    pos_hint: {'center_x': .5}
    size_hint_x: .98
    size_hint_y: .5

<Day>:
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        anchor_y:'top'
        orientation: "vertical"
        height: root.height
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos

        Label:
            id: L1
            text: ""
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            text_size: self.size
            halign: 'left'
            valign: 'center'
            size_hint_y: .1
            canvas.before:
                Color:
                    rgba: get_color_from_hex(app.OC1)
                Rectangle:
                    size: self.size
                    pos: self.pos

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: eslayout
                size_hint_y: None
                padding: dp(5), dp(5)
                spacing: dp(5)
                anchor_y:'top'
                orientation: "vertical"
                height: 20
                size_hint_x: 1


                BoxLayout:
                    id: box
                    padding: dp(5), dp(5)
                    spacing: dp(5)
                    anchor_y:'top'
                    orientation: "vertical"
                    size_hint_y: 1



        BoxLayout:
            orientation: "horizontal"
            size_hint_y: .1

            MDRectangleFlatButton:
                text: root.CloseButton
                text_color: get_color_from_hex(app.TC)
                md_bg_color: get_color_from_hex(app.PBC)
                on_release:
                    root.close_btn_touch_up()
            BoxLayout:


<EVENT>:
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        anchor_y:'top'
        orientation: "vertical"


        Label:
            id: L1
            text: ""
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            text_size: self.size
            halign: 'left'
            valign: 'center'
            size_hint_y: .4
            canvas.before:
                Color:
                    rgba: get_color_from_hex(app.OC1)
                Rectangle:
                    size: self.size
                    pos: self.pos


        GridLayout:
            id: tagbox
            padding: dp(5), dp(5)
            spacing: dp(5)
            anchor_y:'top'
            cols: 3
            orientation: "lr-tb"
            col_force_default: True
            col_default_width: '90dp'
            row_force_default: True
            row_default_height: '35dp'
            height: 0


<TAG>:
    text: root.TagText
    color: get_color_from_hex(app.TC)
    size_hint: None, None
    size: 90, 30
    anchor_y:'top'
    anchor_x:'left'
    canvas.before:
        Color:
            rgba: get_color_from_hex(app.AC)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10,]



<NEWEVENT>:
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos

        BoxLayout:
            size_hint_y: .10
            orientation: "vertical"


            Label:
                text: root.Name
                font_size: app.font_size
                color: get_color_from_hex(app.TC)
                text_size: self.size
                halign: 'left'
                valign: 'center'

            TextInput:
                id: name
                multiline: False
                font_size: app.font_size
                text_size: self.size
                cursor_color: get_color_from_hex(app.TC)
                foreground_color: get_color_from_hex(app.TC)
                size_hint_y: None
                height: sp(32)
                background_color: get_color_from_hex(app.BGC)


        BoxLayout:
            orientation: "vertical"
            spacing: dp(5)
            size_hint_y: 0.50
            Label:
                text: root.Tags
                font_size: app.font_size
                text_size: self.size
                color: get_color_from_hex(app.TC)
                halign: 'left'
                valign: 'center'
                size_hint_y: 0.2
            GridLayout:
                id: tagbox
                cols: 3
                spacing: dp(5)
                orientation: "lr-tb"


        BoxLayout:
            orientation: "vertical"
            spacing: dp(5)
            padding: dp(5)
            size_hint_y: .2

            BoxLayout:
                size_hint_y: .45
                size_hint_x: .30
                MDRectangleFlatButton:
                    text: root.TimeS
                    font_size: app.font_size
                    id: times
                    text_color: get_color_from_hex(app.TC)
                    md_bg_color: get_color_from_hex(app.PBC)
                    size_hint_y: 1
                    size_hint_x: .45
                    on_release:
                        root.set_time(True)
                Widget:
                    size_hint_y: 1
                    size_hint_x: .1

                MDRectangleFlatButton:
                    text: root.TimeF
                    font_size: app.font_size
                    id: timef
                    text_color: get_color_from_hex(app.TC)
                    md_bg_color: get_color_from_hex(app.PBC)
                    size_hint_y: 1
                    size_hint_x: .45
                    on_release:
                        root.set_time(False)

            BoxLayout:
                size_hint_y: .45
                size_hint_x: 1
                MDRectangleFlatButton:
                    text: root.Date
                    font_size: app.font_size
                    id: date
                    text_color: get_color_from_hex(app.TC)
                    md_bg_color: get_color_from_hex(app.PBC)
                    size_hint_x: .45
                    size_hint_y: 1
                    on_release:
                        root.set_date()

                BoxLayout:
                    size_hint_x: .85
                MDFloatingActionButton:
                    size_hint_x: .2
                    size_hint_y: .9
                    icon: "plus"
                    md_bg_color: get_color_from_hex(app.PBC)
                    icon_color: get_color_from_hex(app.TC)
                    pos_hint: {"center_x": .9, "center_y": .5}
                    elevation: 0
                    on_release:
                        root.rec_btn_touch_up()

        BoxLayout:
            size_hint_y: .10

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: .1

            MDRectangleFlatButton:
                text: root.CloseButton
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                md_bg_color: get_color_from_hex(app.PBC)
                on_release:
                    root.close_btn_touch_up()
            BoxLayout:
            MDRectangleFlatButton:
                text: root.OkButton
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                md_bg_color: get_color_from_hex(app.PBC)
                on_release:
                    root.ok_btn_touch_up()

<CheckItem>
    adaptive_height: True
    md_bg_color: get_color_from_hex(app.SBC)

    MDCheckbox:
        id:check
        size_hint: None, None
        color_active: get_color_from_hex(app.AC)
        size: "48dp", "48dp"
        pos_hint: {"center_y": .5}
        active: root.checked
        size_hint_x: .2

    MDLabel:
        text: root.text
        font_size: app.font_size
        adaptive_height: True
        color: get_color_from_hex(app.TC)
        pos_hint: {"center_y": .5}
        size_hint_x: .8

<GCheckItem>
    adaptive_height: True
    md_bg_color: get_color_from_hex(app.SBC)

    MDCheckbox:
        id:check
        group: root.group
        size_hint: None, None
        color_active: get_color_from_hex(app.AC)
        size: "48dp", "48dp"
        active: root.checked
        size_hint_x: .2

    MDLabel:
        text: root.text
        font_size: app.font_size
        adaptive_height: True
        color: get_color_from_hex(app.TC)
        pos_hint: {"center_y": .5}
        size_hint_x: .8


<Form>
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: questionsbox
                size_hint_y: None
                spacing: dp(5)
                anchor_y:'top'
                orientation: "vertical"
                height: 0
                size_hint_x: 1

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: .1
            padding: dp(5)

            MDRaisedButton:
                text: root.ButtonText
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                size_hint_y: 1
                on_release:
                    root.close_btn_touch_up(root.ResultPath)



<SimpleQuestion>
    orientation: "vertical"
    padding: dp(5), dp(10)
    spacing: dp(5)

    MDLabel:
        text: root.text
        font_size: app.font_size
        color: get_color_from_hex(app.TC)
        halign: 'left'
        valign: 'center'
        size_hint_y: 0.4
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.OC1)
            Rectangle:
                size: self.size
                pos: self.pos

    BoxLayout:
        orientation: "horizontal"
        GCheckItem:
            id: check
            text: root.Yes
            group: root.group
        GCheckItem:
            text: root.No
            group: root.group

<RateQuestion>
    orientation: "vertical"
    padding: dp(5), dp(5)
    spacing: dp(5)

    MDLabel:
        text: root.text
        font_size: app.font_size
        color: get_color_from_hex(app.TC)
        halign: 'left'
        valign: 'center'
        size_hint_y: 0.4
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.OC1)
            Rectangle:
                size: self.size
                pos: self.pos

    BoxLayout:
        orientation: "horizontal"

        MDLabel:
            text: root.LL
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'right'
            valign: 'center'
            size_hint_x: 0.2

        MDSlider
            id: rate
            hint: True
            color: get_color_from_hex(app.AC)
            hint_bg_color: get_color_from_hex(app.AC)
            hint_text_color: get_color_from_hex(app.TC)
            thumb_color_active: get_color_from_hex(app.PBC)
            thumb_color_inactive: get_color_from_hex(app.SBC)
            hint_radius: [6, 0, 6, 0]
            min:0
            max:10
            size_hint_x: 0.6
            step: 1

        MDLabel:
            text: root.RL
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_x: 0.2


<Reg>
    BoxLayout:
        padding: dp(0), dp(10)
        spacing: dp(5)
        anchor_y:'top'
        orientation: "vertical"
        height: root.height
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)

            Rectangle:
                size: self.size
                pos: self.pos

        MDLabel:
            text: root.LabelText
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'center'
            valign: 'center'


        MDRaisedButton:
            text: root.ButtonText
            font_size: app.font_size
            text_color: get_color_from_hex(app.TC)
            halign: 'center'
            valign: 'center'
            md_bg_color: get_color_from_hex(app.PBC)
            pos_hint: {'center_x': .5}
            size_hint_x: .98
            size_hint_y: .1
            on_release:
                root.reg_btn_touch_up()


<DateDialog>
    primary_color: get_color_from_hex(app.PBC)
    accent_color: get_color_from_hex(app.AC)
    selector_color: get_color_from_hex(app.SBC)
    text_toolbar_color: get_color_from_hex(app.TC)
    text_color: get_color_from_hex(app.TC)
    text_current_color: get_color_from_hex(app.TC)
    text_button_color: get_color_from_hex(app.TC)
    font_size: app.font_size

<TimeDialog>
    primary_color: get_color_from_hex(app.BGC)
    accent_color: get_color_from_hex(app.AC)
    text_button_color: get_color_from_hex(app.TC)
    text_toolbar_color: get_color_from_hex(app.TC)
    font_size: app.font_size


<Profile>
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.2
            MDLabel:
                text: root.ProfileHead
                font_size: app.font_size
                color: get_color_from_hex(app.TC)
                halign: 'left'
                valign: 'center'
                size_hint_x: 0.8
            MDFloatingActionButton:
                size_hint_y: 0.7
                width: self.height
                icon: "cog"
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                icon_color: get_color_from_hex(app.TC)
                pos_hint: {"center_x": .5, "center_y": .5}
                on_release:
                    root.settings_btn_touch_up()

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            GridLayout:
                id: skillsbox
                padding: dp(0), dp(10)
                spacing: dp(5)
                anchor_y:'top'
                cols: 2
                size_hint_y: None
                height: 0

        BoxLayout:
            size_hint_y: 0.2

        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.ButtonText
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()



<SkillButton>
    icon: root.icon
    text: root.text
    text_color: get_color_from_hex(app.TC)
    icon_color: get_color_from_hex(app.TC)
    halign: 'left'
    valign: 'center'
    md_bg_color: get_color_from_hex(app.SBC)
    pos_hint: {'center_x': .5}
    size_hint_x: .98
    size_hint_y: .2
    font_size: app.font_size
    on_release:
        root.showinfo()


<ModalCase>
    pos_hint: {'center_x': .5, 'center_y': .6}
    size_hint_x: .98
    size_hint_y: .25
    padding: dp(5), dp(5)
    spacing: dp(5)
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: get_color_from_hex(app.OC1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10,]

    MDLabel:
        text: root.name
        font_size: app.font_size
        color: get_color_from_hex(app.TC)
        halign: 'center'
        valign: 'center'
        size_hint_y: 0.4

    MDLabel:
        text: root.text
        font_size: app.font_size
        color: get_color_from_hex(app.TC)
        halign: 'center'
        valign: 'center'
        size_hint_y: 0.4

    MDRaisedButton:
        text: root.CloseButtonText
        font_size: app.font_size
        text_color: get_color_from_hex(app.TC)
        halign: 'center'
        valign: 'center'
        md_bg_color: get_color_from_hex(app.PBC)
        pos_hint: {'center_x': .5}
        size_hint_x: .98
        size_hint_y: .2
        on_release:
            root.close_btn_touch_up()


<RateScreen>
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        MDLabel:
            text: root.Header
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_y: 0.1
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: ratebox
                padding: dp(0), dp(10)
                spacing: dp(5)
                anchor_y:'top'
                orientation: "vertical"
                size_hint_y: None
                height: 0
        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.ButtonText
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()


<RateButton>
    text: root.text
    font_size: app.font_size
    text_color: get_color_from_hex(app.TC)
    halign: 'left'
    valign: 'center'
    md_bg_color: get_color_from_hex(app.SBC)
    pos_hint: {'center_x': .5}
    size_hint_x: .98
    size_hint_y: .2
    on_release:
        root.rate_btn_touch_up(root.eventid)


<TaskScreen>:
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        MDLabel:
            font_size: app.font_size
            text: root.TaskHeader
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_y: 0.1
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: taskbox
                padding: dp(0), dp(10)
                spacing: dp(5)
                anchor_y:'top'
                orientation: "vertical"
                size_hint_y: None
                height: 0

        BoxLayout:
            size_hint_y: 0.1

        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.CloseButton
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()

    MDFloatingActionButton:
        width: self.height
        icon: "plus"
        md_bg_color: get_color_from_hex(app.PBC)
        icon_color: get_color_from_hex(app.TC)
        pos_hint: {"center_x": .90, "center_y": .15}
        on_release:
            root.newtask_btn_touch_up()

    MDFloatingActionButton:
        width: self.height
        icon: "chart-line"
        md_bg_color: get_color_from_hex(app.PBC)
        icon_color: get_color_from_hex(app.TC)
        pos_hint: {"center_x": .10, "center_y": .15}
        on_release:
            root.stat_btn_touch_up()

<Task>:
    orientation: "horizontal"
    padding: dp(5), dp(5)
    spacing: dp(10)
    canvas.before:
        Color:
            rgba: get_color_from_hex(app.SBC)
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        size_hint_x: 0.8
        orientation: "vertical"
        MDLabel:
            text: root.name
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            size_hint_y: 0.6

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.4
            spacing: dp(5)

            MDProgressBar:
                id: bar
                color: get_color_from_hex(app.AC)
                back_color: get_color_from_hex(app.OC1)
                size_hint_y: .5
                pos_hint: {'center_y': .5}
                radius: [0, 0, 0, 0]
                min:0
                max:root.max
                value: root.value

            MDFillRoundFlatButton:
                text: root.SubTaskButton
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5, 'center_y': .5}
                size_hint_x: .2
                size_hint_y: 1
                pos_hint: {'center_y': .5}
                on_release:
                    root.subtask_btn_toch_up()


<NewTaskScreen>:
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        MDLabel:
            text: root.Name
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_y: 0.1
        TextInput:
            id: name
            multiline: False
            font_size: app.font_size
            text_size: self.size
            cursor_color: get_color_from_hex(app.AC)
            foreground_color: get_color_from_hex(app.TC)
            size_hint_y: 0.15
            size_hint_x: 0.6
            background_color: get_color_from_hex(app.SBC)
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: newtaskbox
                padding: dp(0), dp(10)
                spacing: dp(5)
                anchor_y:'top'
                orientation: "vertical"
                size_hint_y: None
                height: 0

        BoxLayout:


        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.AddButton
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()

    MDFloatingActionButton:
        with: self.height
        icon: "plus"
        md_bg_color: get_color_from_hex(app.PBC)
        icon_color: get_color_from_hex(app.TC)
        pos_hint: {"center_x": .85, "center_y": .15}
        on_release:
            root.newsubtask_btn_touch_up()

<NewSubTask>:
    orientation: "horizontal"
    padding: dp(5), dp(5)
    spacing: dp(10)
    canvas.before:
        Color:
            rgba: get_color_from_hex(app.SBC)
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        size_hint_x: 0.8
        orientation: "vertical"
        MDLabel:
            text: root.Name
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            size_hint_y: 0.4


        TextInput:
            id: name
            multiline: False
            size_hint_y: 0.6
            font_size: app.font_size
            text_size: self.size
            cursor_color: get_color_from_hex(app.AC)
            foreground_color: get_color_from_hex(app.TC)
            background_color: get_color_from_hex(app.SBC)


<SubTaskScreen>
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        MDLabel:
            text: root.text
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_y: 0.1
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: subtaskbox
                padding: dp(0), dp(10)
                spacing: dp(5)
                anchor_y:'top'
                orientation: "vertical"
                size_hint_y: None
                height: 0

        BoxLayout:

        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.CloseButton
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()

<SubTask>:
    orientation: "horizontal"
    padding: dp(5), dp(5)
    spacing: dp(10)
    canvas.before:
        Color:
            rgba: get_color_from_hex(app.SBC)
        Rectangle:
            size: self.size
            pos: self.pos

    CheckItem:
        text: root.text
        id: check
        checked: root.checked
        size_hint_y: 0.8
        pos_hint: {"center_y": .5}


<SettingScreen>
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        MDLabel:
            text: root.Header
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_y: 0.1
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                id: subtaskbox
                padding: dp(0), dp(10)
                spacing: dp(10)
                anchor_y:'top'
                orientation: "vertical"
                size_hint_y: None
                height: 130


                MDRaisedButton:
                    text: root.LangName
                    font_size: app.font_size
                    text_color: get_color_from_hex(app.TC)
                    halign: 'center'
                    valign: 'center'
                    md_bg_color: get_color_from_hex(app.PBC)
                    pos_hint: {'center_x': .5}
                    size_hint_x: .98
                    on_release:
                        root.change_lang_btn_touch_up()

                MDRaisedButton:
                    text: root.Theme
                    font_size: app.font_size
                    text_color: get_color_from_hex(app.TC)
                    halign: 'center'
                    valign: 'center'
                    md_bg_color: get_color_from_hex(app.PBC)
                    pos_hint: {'center_x': .5}
                    size_hint_x: .98
                    on_release:
                        root.change_theme_btn_touch_up()

        BoxLayout:

        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.CloseButtonText
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()


<StatScreen>
    BoxLayout:
        padding: dp(5), dp(5)
        spacing: dp(5)
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: get_color_from_hex(app.BGC)
            Rectangle:
                size: self.size
                pos: self.pos
        MDLabel:
            text: root.Header
            id:testlb
            font_size: app.font_size
            color: get_color_from_hex(app.TC)
            halign: 'left'
            valign: 'center'
            size_hint_y: 0.1

        BoxLayout:
            id:graph

        BoxLayout:
            padding: dp(5), dp(5)
            spacing: dp(5)
            orientation: "horizontal"
            size_hint_y: 0.1
            MDRaisedButton:
                text: root.CloseButton
                font_size: app.font_size
                text_color: get_color_from_hex(app.TC)
                halign: 'center'
                valign: 'center'
                md_bg_color: get_color_from_hex(app.PBC)
                pos_hint: {'center_x': .5}
                size_hint_x: .98
                on_release:
                    root.close_btn_touch_up()

<FloatLabel>:
    pos_hint: {'center_x': .5, 'center_x': .5}
    font_size: app.font_size
    text: root.LabelText
    id:FL
    color: get_color_from_hex(app.TC)
